
#net.minecraft.scalar.cutall.mod_CutAllSMP
[configuration]
	#String: "iron_axe, wooden_axe, stone_axe, diamond_axe, golden_axe, netherite_axe"
	itemIds = "iron_axe, wooden_axe, stone_axe, diamond_axe, golden_axe, netherite_axe"
	#String: "oak_log,spruce_log,birch_log,jungle_log,acacia_log,dark_oak_log,stripped_spruce_log,stripped_birch_log,stripped_jungle_log,stripped_acacia_log,stripped_dark_oak_log,stripped_oak_log,oak_wood,spruce_wood,birch_wood,jungle_wood,acacia_wood,dark_oak_wood,stripped_oak_wood,stripped_spruce_wood,stripped_birch_wood,stripped_jungle_wood,stripped_acacia_wood,stripped_dark_oak_wood,crimson_stem,warped_stem,crimson_hyphae,warped_hyphae"
	blockIds = "oak_log,spruce_log,birch_log,jungle_log,acacia_log,dark_oak_log,stripped_spruce_log,stripped_birch_log,stripped_jungle_log,stripped_acacia_log,stripped_dark_oak_log,stripped_oak_log,oak_wood,spruce_wood,birch_wood,jungle_wood,acacia_wood,dark_oak_wood,stripped_oak_wood,stripped_spruce_wood,stripped_birch_wood,stripped_jungle_wood,stripped_acacia_wood,stripped_dark_oak_wood,crimson_stem,warped_stem,crimson_hyphae,warped_hyphae"
	#String: "oak_leaves,spruce_leaves,birch_leaves,jungle_leaves,acacia_leaves,dark_oak_leaves"
	leavesIds = "oak_leaves,spruce_leaves,birch_leaves,jungle_leaves,acacia_leaves,dark_oak_leaves"
	#String: ""
	nondestructiveItemIDs = ""
	#Integer: 3
	leavesRange = 3
	#String: "KEY_C"
	Key = "KEY_C"
	#Integer: 0
	Limiter = 0
	#Integer: 0
	#0:not decrease durability 1,2:decrease durability(1=until whole blocks 2=until break an item)
	Durability = 0
	#Boolean: true
	DropGather = true
	#Boolean: false
	DestroyUnder = false
	#Boolean: true
	StartMode = true
	#String: "mod_cutall"
	channelName = "mod_cutall"

